import "server-only";
import { TEST_MODE, TEST_USER_COOKIE, encodeTestModeIdentity } from "@/lib/test-mode";
import { getSupabaseAuthAdminClient } from "@/lib/supabase/admin-client";
import { createClient } from "@/lib/supabase/server";

/**
 * Sale-Ready Phase B, PR1 (Password Recovery). Wraps Supabase Auth's own
 * real recovery-token mechanism (admin.generateLink()'s hashed_token,
 * verified via auth.verifyOtp()) — never a custom token scheme. This app
 * sends its own branded email (src/lib/email/password-reset.ts) rather
 * than relying on Supabase's own SMTP delivery/template, so the link the
 * user actually receives points at this app's own /auth/confirm route
 * with `token_hash` — never Supabase's own action_link, which would
 * depend on the project's configured redirect-URL allowlist (a manual
 * dashboard step this approach deliberately avoids needing at all).
 *
 * TEST_MODE gets its own in-memory token store, the same "no real
 * Supabase Auth reachable in this sandbox" reasoning as every other
 * TEST_MODE branch in this app (src/lib/test-mode.ts, src/lib/storage/
 * test-storage.ts) — real Supabase's own token expiry/single-use
 * semantics are mirrored here, not skipped.
 */

const TEST_TOKEN_TTL_MS = 60 * 60 * 1000; // 1 hour — matches Supabase's own default recovery link TTL.

type TestTokenEntry = { email: string; expiresAt: number };

// globalThis, not a module-level variable: Next.js compiles Server Actions
// and Route Handlers into separate bundle graphs even within one `next
// start` process (verified empirically for src/lib/storage/test-storage.ts,
// the same class of problem) — a plain module-level Map would end up as
// two independent instances across that split, so a token generated by
// the forgot-password Server Action would never be found by the
// /auth/confirm Route Handler.
const globalForRecoveryTokens = globalThis as unknown as {
  e2eRecoveryTokens: Map<string, TestTokenEntry> | undefined;
};
const testTokenStore = globalForRecoveryTokens.e2eRecoveryTokens ?? new Map<string, TestTokenEntry>();
globalForRecoveryTokens.e2eRecoveryTokens = testTokenStore;

/**
 * TEST_MODE-only, deliberately deterministic (real Supabase tokens are
 * opaque and random; this one is a plain base64url of the email) — the
 * same trade-off src/lib/test-mode.ts's own encodeTestModeIdentity()
 * already makes, and for the same reason: an E2E test has no real
 * mailbox to read a real link out of, so it needs to independently
 * compute the exact token its own forgot-password submission caused this
 * function to generate, mirroring this one encoding in Playwright's own
 * Node process (see test/e2e/password-reset.spec.ts's own local copy).
 */
function testTokenHash(email: string): string {
  return Buffer.from(email, "utf8").toString("base64url");
}

export type GenerateRecoveryTokenResult = { ok: true; tokenHash: string } | { ok: false };

/**
 * Issues a fresh recovery token for the given email. Never throws — a
 * misconfigured admin client or a Supabase API failure both come back as
 * `{ ok: false }`, which callers (requestPasswordResetCore) treat exactly
 * like "email not found": the caller-facing response must stay identical
 * either way, to prevent enumeration.
 */
export async function generateRecoveryToken(email: string): Promise<GenerateRecoveryTokenResult> {
  if (TEST_MODE) {
    const tokenHash = testTokenHash(email);
    testTokenStore.set(tokenHash, { email, expiresAt: Date.now() + TEST_TOKEN_TTL_MS });
    return { ok: true, tokenHash };
  }

  try {
    const admin = getSupabaseAuthAdminClient();
    const { data, error } = await admin.auth.admin.generateLink({ type: "recovery", email });
    const tokenHash = data?.properties?.hashed_token;
    if (error || !tokenHash) return { ok: false };
    return { ok: true, tokenHash };
  } catch {
    return { ok: false };
  }
}

export type VerifyRecoveryTokenResult = { ok: true; email: string } | { ok: false };

/**
 * Verifies a recovery token and, on success, establishes a real session —
 * in production via Supabase's own auth.verifyOtp() (whose session cookies
 * are persisted through the exact same request-scoped client/cookie
 * adapter every other authenticated flow in this app already uses), in
 * TEST_MODE via the identical identity-cookie bypass every other
 * TEST_MODE-reachable authenticated flow already relies on (see
 * src/lib/test-mode.ts) — this function resolves the local User/PortalUser
 * id itself so the TEST_MODE session it sets up is a real, usable
 * identity, not just an email string.
 *
 * Single-use: a TEST_MODE token is deleted from the store the moment it's
 * looked up, matching Supabase's own real one-time-use recovery tokens.
 */
export async function verifyRecoveryToken(tokenHash: string): Promise<VerifyRecoveryTokenResult> {
  if (TEST_MODE) {
    const entry = testTokenStore.get(tokenHash);
    if (!entry) return { ok: false };
    testTokenStore.delete(tokenHash);
    if (Date.now() > entry.expiresAt) return { ok: false };
    return { ok: true, email: entry.email };
  }

  try {
    const supabase = await createClient();
    const { data, error } = await supabase.auth.verifyOtp({ type: "recovery", token_hash: tokenHash });
    if (error || !data.user?.email) return { ok: false };
    return { ok: true, email: data.user.email };
  } catch {
    return { ok: false };
  }
}

export type TestModeRecoveryCookie = {
  name: string;
  value: string;
  options: { httpOnly: true; sameSite: "lax"; secure: boolean; path: "/" };
};

/**
 * TEST_MODE-only: the identity-cookie bypass session for a verified
 * recovery token, given the local id the caller already resolved (the
 * /auth/confirm route resolves User/PortalUser by email anyway, to decide
 * which page to redirect to — this reuses that same lookup rather than
 * repeating it here). Returns the cookie to set rather than setting it
 * itself: a Route Handler's next/headers cookies().set() does not
 * reliably attach to a NextResponse object the handler constructs and
 * returns itself (verified empirically) — the route must call
 * `response.cookies.set(...)` directly on the exact NextResponse it
 * returns, so this hands back a plain, applicable value instead of trying
 * to set it here. Returns null outside TEST_MODE, since a real verifyOtp()
 * call already established the real session as a side effect of
 * verifyRecoveryToken() itself, through the ordinary request-scoped
 * cookie adapter every other authenticated flow in this app already uses.
 *
 * `secure` is hardcoded false, not derived from NODE_ENV like
 * current-user.ts's own ACTIVE_ORG_COOKIE options — deliberately: the E2E
 * webServer runs `next start`, which sets NODE_ENV=production internally
 * even though Playwright talks to it over plain http://127.0.0.1 (verified
 * empirically: a Secure cookie is silently dropped by the browser over
 * that connection, so the session this cookie exists to establish would
 * never actually take). TEST_MODE never runs against a real HTTPS
 * deployment (see src/lib/test-mode.ts's own doc comment), so there is no
 * real-production case this could ever weaken — matches
 * test/support/e2e-session.ts's own injectTestSession, which makes the
 * identical protocol-based (not NODE_ENV-based) call for the same reason.
 */
export function testModeRecoveryCookie(identity: { id: string; email: string }): TestModeRecoveryCookie | null {
  if (!TEST_MODE) return null;

  return {
    name: TEST_USER_COOKIE,
    value: encodeTestModeIdentity(identity),
    options: {
      httpOnly: true,
      sameSite: "lax",
      secure: false,
      path: "/",
    },
  };
}
