// src/app/(portal)/portal/client/invoices/page.tsx
import { auth } from "@/lib/auth";
import { redirect } from "next/navigation";
import { prisma } from "@/lib/db";
import Link from "next/link";
import { FileText, CheckCircle2 } from "lucide-react";


export const metadata = { title: "Invoices" };

function fmt(n: number) {
  return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(n);
}
function fmtDate(d: Date) {
  return new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric" }).format(new Date(d));
}

export default async function ClientInvoicesPage() {
  const session = await auth();
  if (!session?.user?.id) redirect("/portal/login");

  const invoices = await prisma.invoice.findMany({
    where: { clientId: session.user.id, deletedAt: null },
    orderBy: { createdAt: "desc" },
    include: {
      order: { select: { serviceTitle: true } },
      lineItems: true,
    },
  });

  const invoicesWithTotals = invoices.map((inv) => ({
    ...inv,
    total: inv.lineItems.reduce((sum, item) => sum + Number(item.amount), 0),
  }));

  const unpaidCount = invoicesWithTotals.filter((i) => !i.isPaid).length;

  return (
    <div className="portal-page">
      <div className="page-header">
        <div>
          <h1 className="page-header-title">Invoices</h1>
          <p className="page-header-sub">
            {invoices.length} total invoice{invoices.length !== 1 ? "s" : ""}
            {unpaidCount > 0 && <span style={{ color: "var(--warning)" }}> · {unpaidCount} unpaid</span>}
          </p>
        </div>
      </div>

      {invoicesWithTotals.length === 0 ? (
        <div className="card">
          <div className="empty-state">
            <FileText size={40} className="empty-state-icon" />
            <div className="empty-state-title">No invoices yet</div>
            <p className="empty-state-text">Your invoices will appear here when they are generated by the team.</p>
          </div>
        </div>
      ) : (
        <div className="table-wrapper" style={{ borderRadius: 8, border: "1px solid var(--neutral-200)", overflow: "hidden", background: "#fff" }}>
          <table className="portal-table" style={{ width: "100%", borderCollapse: "collapse" }}>
            <thead style={{ background: "var(--neutral-50)", borderBottom: "1px solid var(--neutral-200)", textTransform: "uppercase", fontSize: 11, fontWeight: 700, color: "var(--neutral-500)", letterSpacing: "0.05em" }}>
              <tr>
                <th style={{ padding: "16px 24px", textAlign: "left", whiteSpace: "nowrap" }}>Invoice</th>
                <th style={{ padding: "16px 24px", textAlign: "left", whiteSpace: "nowrap" }}>Project</th>
                <th style={{ padding: "16px 24px", textAlign: "left", whiteSpace: "nowrap" }}>Total Amount</th>
                <th style={{ padding: "16px 24px", textAlign: "left", whiteSpace: "nowrap" }}>Due Date</th>
                <th style={{ padding: "16px 24px", textAlign: "left", whiteSpace: "nowrap" }}>Paid</th>
                <th style={{ padding: "16px 24px", textAlign: "left", whiteSpace: "nowrap" }}>Due</th>
                <th style={{ padding: "16px 24px", textAlign: "left", whiteSpace: "nowrap" }}>Status</th>
                <th style={{ padding: "16px 24px", textAlign: "right", whiteSpace: "nowrap" }}>Actions</th>
              </tr>
            </thead>
            <tbody>
              {invoicesWithTotals.map((inv) => {
                const amountPaid = inv.isPaid ? inv.total : Number(inv.amountPaid || 0);
                const amountDue = Math.max(0, inv.total - amountPaid);
                const isPartiallyPaid = !inv.isPaid && amountPaid > 0;
                
                return (
                  <tr key={inv.id} style={{ borderBottom: "1px solid var(--neutral-100)", fontSize: 13 }}>
                    <td style={{ padding: "16px 24px", fontWeight: 700, color: "var(--neutral-900)" }}>{inv.invoiceNumber}</td>
                    <td style={{ padding: "16px 24px", color: "var(--neutral-600)" }}>{inv.order?.serviceTitle ?? "—"}</td>
                    <td style={{ padding: "16px 24px", fontWeight: 700, color: "var(--neutral-900)" }}>{fmt(inv.total)}</td>
                    <td style={{ padding: "16px 24px", color: "var(--neutral-500)" }}>{fmtDate(inv.dueDate)}</td>
                    <td style={{ padding: "16px 24px", fontWeight: 700, color: "#16a34a" }}>{fmt(amountPaid)}</td>
                    <td style={{ padding: "16px 24px", fontWeight: 700, color: amountDue > 0 ? "#ea580c" : "#6b7280" }}>{fmt(amountDue)}</td>
                    <td style={{ padding: "16px 24px" }}>
                      {inv.isPaid ? (
                        <span style={{ display: "inline-flex", alignItems: "center", gap: 5, background: "#dcfce7", color: "#16a34a", padding: "3px 10px", borderRadius: 20, fontSize: 11, fontWeight: 700 }}>
                          <CheckCircle2 size={11} /> Paid
                        </span>
                      ) : isPartiallyPaid ? (
                        <span style={{ display: "inline-flex", alignItems: "center", gap: 5, background: "#dbeafe", color: "#1d4ed8", padding: "3px 10px", borderRadius: 20, fontSize: 11, fontWeight: 700 }}>
                          ◉ Partially Paid
                        </span>
                      ) : (
                        <span style={{ display: "inline-flex", alignItems: "center", gap: 5, background: "#fef3c7", color: "#d97706", padding: "3px 10px", borderRadius: 20, fontSize: 11, fontWeight: 700 }}>
                          ⊙ Unpaid
                        </span>
                      )}
                    </td>
                    <td style={{ padding: "16px 24px", textAlign: "right" }}>
                      <div style={{ display: "flex", gap: 8, justifyContent: "flex-end", alignItems: "center" }}>
                        <Link href={`/portal/client/invoices/${inv.id}`} className="btn btn-outline btn-sm">View Details</Link>
                      </div>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}
