/*
  Invoice System Official Slice 5c — organization-wide Invoice-number
  uniqueness (docs/invoicing-architecture.md §4.5/§12.5). Replaces the
  existing "Invoice_clientId_invoiceNumber_key" unique index (scoped to a
  single Client) with "Invoice_organizationId_invoiceNumber_key" (scoped to
  the whole organization), so two different Clients within the same
  organization can no longer share an Invoice number.

  Provenance of every statement below, stated precisely (the correction
  audit that preceded this migration found the earlier design draft's own
  terminology and ordering both needed a fix — recorded here rather than
  repeated):

  - The pre-alter verification guard (the DO $$ ... $$ block) is entirely
    hand-authored. It is a plain PL/pgSQL count-and-abort check, never a
    Prisma-generated statement.
  - The two DDL statements — CREATE UNIQUE INDEX and DROP INDEX — are
    exactly what this repository's own installed Prisma generates for
    this schema change, obtained via `prisma migrate diff --from-schema
    <pre-5c-schema> --to-schema <post-5c-schema> --script` (no database
    connection), never hand-guessed. This project's `@@unique` has always
    compiled to a bare CREATE UNIQUE INDEX / DROP INDEX pair — never an
    ALTER TABLE ADD/DROP CONSTRAINT — confirmed directly against this
    migration's own predecessor, `20260729033746_invoice_number_unique_
    per_client`, which used the identical DROP INDEX / CREATE UNIQUE INDEX
    shape for the client-scoped constraint this migration now replaces.
  - Prisma's own generated script order is DROP-old-index first, then
    CREATE-new-index. That order is deliberately NOT used here: dropping
    the old index first would open a real window with zero Invoice-number
    uniqueness protection of any kind before the new index exists. Since
    every row satisfying the new (organizationId, invoiceNumber) tuple
    also necessarily satisfies the old (clientId, invoiceNumber) tuple
    (see the residual-risk note below for exactly why, and its limit),
    the new index is a strict strengthening of the old one for any data
    that passes the guard below — so creating it first, then dropping the
    old one, closes that window entirely: at every point in this
    migration, at least one of the two indexes is live.
  - This migration performs no UPDATE, INSERT, DELETE, backfill,
    auto-rename, or silent repair of any Invoice row, and no ALTER TABLE
    of any kind — only the guard (read-only) and the two index
    statements above.
  - No explicit top-level BEGIN/COMMIT, matching the empirically
    reverified (not merely re-cited) finding already established by
    `20260911090000_repair_invoice_organization_scope` and reused by every
    guarded migration since: Prisma Migrate already wraps a migration.sql
    file's statements in its own transaction when applied via `prisma
    migrate deploy`. This was re-proven directly this session (a
    disposable, isolated PGlite instance; a throwaway probe migration
    with a benign CREATE TABLE followed by a forced RAISE EXCEPTION; the
    CREATE TABLE did not survive the forced failure) rather than assumed
    from the historical comment alone.
  - Case sensitivity is unchanged: `invoiceNumber` remains a plain
    TEXT/String column with no citext type and no lower()-based functional
    index anywhere in this schema's history — this migration preserves
    exact case-sensitive comparison; it does not introduce
    case-insensitive matching.

  Residual risk, stated explicitly rather than assumed away: there is no
  permanent database-level constraint (no composite foreign key, no CHECK
  constraint, no trigger) tying Invoice.organizationId to the organization
  that actually owns Invoice.clientId. That consistency is, and after this
  migration remains, an operationally-maintained invariant — verified for
  all pre-existing rows once by `20260911090000_repair_invoice_
  organization_scope`'s own guard/backfill, and maintained going forward
  only by the two Invoice writers (`src/app/(dashboard)/invoices/new/
  actions.ts`, `src/app/(dashboard)/invoices/[id]/edit/actions.ts`), which
  both independently re-derive organizationId from the same verified
  Project/Client lookup. Adding a permanent composite-FK/CHECK enforcement
  of this relationship is deliberately out of this migration's scope
  (Slice 5c, §12.5) — the guard below re-verifies this exact invariant
  against real data immediately before creating the new index, which is
  the bounded, disclosed mitigation this migration relies on instead of a
  schema-level guarantee.
*/

-- Pre-alter verification guard (hand-authored — never generated by
-- Prisma). Every currently-existing Invoice row must, together:
--   1. never share its (organizationId, invoiceNumber) pair with any
--      other Invoice row in the same organization;
--   2. never have a blank or whitespace-only invoiceNumber;
--   3. never disagree with its own Project's or Client's organizationId.
-- Never coalesces, never renames, never repairs — only verifies, then
-- aborts loudly (count-only, no invoice number/id/Client/organization
-- value of any kind) if any of the three does not hold.
DO $$
DECLARE
  duplicate_group_count integer;
  blank_invoice_number_count integer;
  ownership_inconsistency_count integer;
BEGIN
  SELECT COUNT(*) INTO duplicate_group_count
  FROM (
    SELECT 1
    FROM "Invoice"
    GROUP BY "organizationId", "invoiceNumber"
    HAVING COUNT(*) > 1
  ) dupes;

  SELECT COUNT(*) INTO blank_invoice_number_count
  FROM "Invoice"
  WHERE TRIM("invoiceNumber") = '';

  SELECT COUNT(*) INTO ownership_inconsistency_count
  FROM "Invoice" i
  JOIN "Project" p ON p.id = i."projectId"
  JOIN "Client" c ON c.id = i."clientId"
  WHERE i."organizationId" IS DISTINCT FROM p."organizationId"
     OR i."organizationId" IS DISTINCT FROM c."organizationId";

  IF duplicate_group_count > 0 OR blank_invoice_number_count > 0 OR ownership_inconsistency_count > 0 THEN
    RAISE EXCEPTION 'Invoice Slice 5c organization-wide invoiceNumber uniqueness contract aborted: % duplicate (organizationId, invoiceNumber) group(s), % blank/whitespace-only invoiceNumber row(s), % ownership-inconsistent row(s) (Invoice.organizationId disagreeing with its Project.organizationId or Client.organizationId). Resolve these rows manually before re-running this migration.', duplicate_group_count, blank_invoice_number_count, ownership_inconsistency_count;
  END IF;
END $$;

-- CreateIndex (Prisma-generated, taken first — see the header comment
-- above for why this is deliberately reordered ahead of the DropIndex
-- below).
CREATE UNIQUE INDEX "Invoice_organizationId_invoiceNumber_key" ON "Invoice"("organizationId", "invoiceNumber");

-- DropIndex (Prisma-generated, taken second, only after the stronger
-- index above already exists).
DROP INDEX "Invoice_clientId_invoiceNumber_key";
